services:
    sensio_labs.job_board_bundle.form.type.announcement:
        class: SensioLabs\JobBoardBundle\Form\Type\AnnouncementType
        tags:
            - { name: form.type, alias: announcement }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
