sensio_labs_job_board:
    resource: "@SensioLabsJobBoardBundle/Controller/"
    type:     annotation
    prefix:   /

backend:
    pattern:  /backend
    defaults: { _controller: SensioLabsBackendBundle:JobAdmin:list, _sonata_admin: sonata.admin.job }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /backend

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /backend

_sensiolabs_connect:
    resource: @SensioLabsConnectBundle/Resources/config/routing.xml

oauth_logout:
    pattern: /session/logout
