security:
    encoders:
        Sensiolabs\JobBoardBundle\Entity\User: plaintext

    providers:
        sensiolabs_connect:
            id: sensiolabs.user_repository

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            sensiolabs_connect:
                check_path:  oauth_callback
                provider:    sensiolabs_connect
            logout:
              path:   oauth_logout
              target: /
            anonymous: true

    access_control:
        - { path: ^/manage, roles: ROLE_USER }
        - { path: ^/backend, role: ROLE_ADMIN }
