security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_CONNECT_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            logout:          ~
            anonymous:       true

    access_control:
        - { path: ^/manage, roles: ROLE_CONNECT_USER }
