<?php

namespace SensioLabs\JobBoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends EntityRepository
{
    public function getList($page = 1, $maxResults = 10)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.status = :status')
            ->setParameter('status', Announcement::STATUS_SAVED)
            ->setFirstResult(($page - 1) * $maxResults)
            ->setMaxResults($maxResults)
        ;

        return $qb->getQuery()->getResult();
    }
}
