<?php

namespace SensioLabs\JobBoardBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\Model\UserInterface;
use SensioLabs\JobBoardBundle\Entity\Job;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    /**
     * @param int $page
     * @param string|null $countryCode
     * @param string|null $contractType
     * @param int $maxResults
     * @return array
     */
    public function getJobs($page = 1, $countryCode = null, $contractType = null, $maxResults = 10)
    {
        if ((int)$page === 0) {
            return;
        }

        $offset = ($page - 1) * $maxResults;

        $qb = $this->createQueryBuilder('a')
            ->where('a.status = :status')
            ->setParameter('status', Job::STATUS_PUBLISHED)
            ->setFirstResult($offset)
            ->setMaxResults($maxResults)
        ;

        $qb = $this->setFiltersQB($qb, $countryCode, $contractType);

        return $qb->getQuery()->getResult();
    }

    public function getFeed($countryCode = null, $contractType = null)
    {
        $qb = $this->createQueryBuilder('a')
            ->where('a.status = :status')
            ->setParameter('status', Job::STATUS_PUBLISHED)
            ->andWhere('a.visibleFrom <= :current_date')
            ->andWhere('a.visibleTo >= :current_date')
            ->setParameter('current_date', new \DateTime())
        ;
        $qb = $this->setFiltersQB($qb, $countryCode, $contractType);

        return $qb->getQuery()->getResult();
    }

    public function setFiltersQB($qb, $countryCode = null, $contractType = null)
    {
        if ($countryCode) {
            $qb->andWhere('a.country = :country_code')
                ->setParameter('country_code', $countryCode)
            ;
        }

        if ($contractType) {
            $qb->andWhere('a.contractType = :contract_type')
                ->setParameter('contract_type', $contractType)
            ;
        }

        return $qb;
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function getByUserQuery(UserInterface $user)
    {
        $qb = $this->createQueryBuilder('j')
            ->where('j.user = :user')
            ->setParameter('user', $user)
        ;

        return $qb->getQuery();
    }

    /**
     * @return array
     */
    public function getCountriesWithJob()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('count(c) as number, c.country')
            ->where('c.status = :status')
            ->setParameter('status', Job::STATUS_PUBLISHED)
            ->groupBy('c.country')
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function getContractTypesWithJob()
    {
        $qb = $this->createQueryBuilder('c')
            ->select('count(c) as number, c.contractType')
            ->where('c.status = :status')
            ->setParameter('status', Job::STATUS_PUBLISHED)
            ->groupBy('c.contractType')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getRandomJob()
    {
        $em = $this->getEntityManager();
        $min = $em->createQuery('SELECT MIN(q.id) FROM SensioLabsJobBoardBundle:Job q')->getSingleScalarResult();
        $max = $em->createQuery('SELECT MAX(q.id) FROM SensioLabsJobBoardBundle:Job q')->getSingleScalarResult();

        $query = $em->createQuery('SELECT q FROM SensioLabsJobBoardBundle:Job q WHERE q.id >= :rand ORDER BY q.id ASC')
            ->setParameter('rand', rand($min, $max))
            ->setMaxResults(1)
            ->getSingleResult()
        ;

        return $query;
    }

    public function hardDelete()
    {
        $qb = $this->createQueryBuilder('j')
            ->delete()
            ->where('j.deletedAt < :current_date')
            ->andWhere('j.status = :status')
            ->setParameter('current_date', new \Datetime('-20 day'))
            ->setParameter('status', Job::STATUS_DELETED)
        ;

        return $qb->getQuery()->getResult();
    }
}
